export const Types = {
  SAVE_GROUP_LIST: "SAVE_GROUP_LIST",
  SAVE_USER_LIST:"SAVE_USER_LIST",
  SAVE_GROUP_MESSAGE:"SAVE_GROUP_MESSAGE",
  SAVE_GROUP_STATUS:"SAVE_GROUP_STATUS",
  SAVE_USER_MESSAGE:"SAVE_USER_MESSAGE",
  SAVE_USER_STATUS:"SAVE_USER_STATUS",
  SAVE_EXISTING_USER:"SAVE_EXISTING_USER"
  };
  